[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
pythonpath = .
xfail_strict = true 

addopts = -v -s --tb=short --strict-markers --alluredir=allure-results

markers =
    api: mark api test cases
    ui: mark ui test cases
    smoke: smoke test
    regression: 回归测试
    credit: 授信模块
    loan: 借款模块
    parabank: Parabank 靶场